# -*- mode: ruby -*-
# vi: set ft=ruby :

CONTROL_IP  = "192.168.56.10"
NGINX_IP    = "192.168.56.11"
WEB1_IP     = "192.168.56.12"
WEB2_IP     = "192.168.56.13"
DB_IP       = "192.168.56.14"

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"
  config.vbguest.auto_update = false if Vagrant.has_plugin?("vagrant-vbguest")

  config.vm.define "control" do |ctl|
    ctl.vm.hostname = "control"
    ctl.vm.network "private_network", ip: CONTROL_IP
    ctl.vm.synced_folder "../ansible", "/home/vagrant/ansible"
    ctl.vm.provider "virtualbox" do |vb|
      vb.name   = "flask-lab-control"
      vb.memory = 512
      vb.cpus   = 1
    end
    ctl.vm.provision "shell", privileged: false, inline: <<-SHELL
sudo apt-get update -y
sudo apt-get install -y ansible sshpass
ssh-keygen -t ed25519 -f ~/.ssh/control_ed25519 -N "" -C "ansible-control"
mkdir -p ~/.vagrant_keys
for host in nginx web1 web2 database; do
  cp /vagrant/.vagrant/machines/${host}/virtualbox/private_key ~/.vagrant_keys/${host}_key
  chmod 600 ~/.vagrant_keys/${host}_key
done
PUBKEY=$(cat ~/.ssh/control_ed25519.pub)
for host in nginx web1 web2 database; do
  case $host in
    nginx)    ip=11 ;;
    web1)     ip=12 ;;
    web2)     ip=13 ;;
    database) ip=14 ;;
  esac
  ssh -i ~/.vagrant_keys/${host}_key -o StrictHostKeyChecking=no vagrant@192.168.56.${ip} "echo '${PUBKEY}' >> ~/.ssh/authorized_keys"
  echo "Key distributed to: ${host}"
done
cat > ~/.ansible.cfg << 'EOF'
[defaults]
inventory         = /home/vagrant/inventory.ini
remote_user       = vagrant
host_key_checking = False
private_key_file  = /home/vagrant/.ssh/control_ed25519

[privilege_escalation]
become        = True
become_method = sudo
become_user   = root
EOF
cat > ~/inventory.ini << 'EOF'
[lb]
nginx ansible_host=192.168.56.11

[webservers]
web1 ansible_host=192.168.56.12
web2 ansible_host=192.168.56.13

[db]
database ansible_host=192.168.56.14

[all:vars]
ansible_user=vagrant
ansible_ssh_private_key_file=/home/vagrant/.ssh/control_ed25519
EOF
echo "=== Ansible control node ready ==="
    SHELL
  end

  config.vm.define "nginx" do |ng|
    ng.vm.hostname = "nginx"
    ng.vm.network "private_network", ip: NGINX_IP
    ng.vm.network "forwarded_port", guest: 80, host: 8080
    ng.vm.provider "virtualbox" do |vb|
      vb.name   = "flask-lab-nginx"
      vb.memory = 512
      vb.cpus   = 1
    end
  end

  config.vm.define "web1" do |web1|
    web1.vm.hostname = "web1"
    web1.vm.network "private_network", ip: WEB1_IP
    web1.vm.provider "virtualbox" do |vb|
      vb.name   = "flask-lab-web1"
      vb.memory = 512
      vb.cpus   = 1
    end
  end

  config.vm.define "web2" do |web2|
    web2.vm.hostname = "web2"
    web2.vm.network "private_network", ip: WEB2_IP
    web2.vm.provider "virtualbox" do |vb|
      vb.name   = "flask-lab-web2"
      vb.memory = 512
      vb.cpus   = 1
    end
  end

  config.vm.define "database" do |db|
    db.vm.hostname = "database"
    db.vm.network "private_network", ip: DB_IP
    db.vm.provider "virtualbox" do |vb|
      vb.name   = "flask-lab-database"
      vb.memory = 768
      vb.cpus   = 1
    end
  end

end