---
- name: Configure database server
  hosts: db
  vars_files:
    - /vagrant/secrets.yml
  roles:
    - database

- name: Configure web servers
  hosts: webservers
  vars_files:
    - /vagrant/secrets.yml
  roles:
    - flask

- name: Configure load balancer
  hosts: lb
  roles:
    - nginx

- name: Security hardening on all nodes
  hosts: all
  roles:
    - security_hardening